2025-07-24 13:35:15,164 - INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
2025-07-24 13:35:26,663 - WARNING - Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E7A22A90A0>: Failed to resolve 'us.i.posthog.com' ([Errno 11002] getaddrinfo failed)")': /batch/
2025-07-24 13:35:26,664 - WARNING - Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E7A22A9250>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")': /batch/
2025-07-24 13:35:26,907 - INFO - Backing off send_request(...) for 0.7s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E7A22A9400>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2025-07-24 13:35:27,595 - WARNING - Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E7A22A9FD0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")': /batch/
2025-07-24 13:35:27,596 - WARNING - Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E7A22AA090>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")': /batch/
2025-07-24 13:35:27,597 - INFO - Backing off send_request(...) for 0.4s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E7A22AA240>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2025-07-24 13:35:27,983 - WARNING - Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E7A22AA7B0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")': /batch/
2025-07-24 13:35:27,984 - WARNING - Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E7A22AA870>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")': /batch/
2025-07-24 13:35:27,986 - INFO - Backing off send_request(...) for 0.8s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E7A22AAA20>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2025-07-24 13:35:28,797 - WARNING - Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E7A22AB0E0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")': /batch/
2025-07-24 13:35:28,798 - WARNING - Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E7A22AB200>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")': /batch/
2025-07-24 13:35:28,801 - ERROR - Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E7A22AB410>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2025-07-24 13:36:12,354 - INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
2025-07-24 13:36:23,079 - WARNING - Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020A916190D0>: Failed to resolve 'us.i.posthog.com' ([Errno 11002] getaddrinfo failed)")': /batch/
2025-07-24 13:36:23,080 - WARNING - Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020A916191F0>: Failed to resolve 'us.i.posthog.com' ([Errno 11002] getaddrinfo failed)")': /batch/
2025-07-24 13:36:23,092 - INFO - Backing off send_request(...) for 0.7s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020A916193A0>: Failed to resolve 'us.i.posthog.com' ([Errno 11002] getaddrinfo failed)")))
2025-07-24 13:36:23,805 - WARNING - Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020A91619DF0>: Failed to resolve 'us.i.posthog.com' ([Errno 11002] getaddrinfo failed)")': /batch/
2025-07-24 13:36:23,807 - WARNING - Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020A91619EB0>: Failed to resolve 'us.i.posthog.com' ([Errno 11002] getaddrinfo failed)")': /batch/
2025-07-24 13:36:23,812 - INFO - Backing off send_request(...) for 0.7s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020A9161A060>: Failed to resolve 'us.i.posthog.com' ([Errno 11002] getaddrinfo failed)")))
2025-07-24 13:36:24,526 - WARNING - Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020A9161A450>: Failed to resolve 'us.i.posthog.com' ([Errno 11002] getaddrinfo failed)")': /batch/
2025-07-24 13:36:24,528 - WARNING - Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020A9161A510>: Failed to resolve 'us.i.posthog.com' ([Errno 11002] getaddrinfo failed)")': /batch/
2025-07-24 13:36:24,533 - INFO - Backing off send_request(...) for 0.8s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020A9161A6C0>: Failed to resolve 'us.i.posthog.com' ([Errno 11002] getaddrinfo failed)")))
2025-07-24 13:36:25,327 - WARNING - Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020A9161AED0>: Failed to resolve 'us.i.posthog.com' ([Errno 11002] getaddrinfo failed)")': /batch/
2025-07-24 13:36:25,330 - WARNING - Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020A9161AFF0>: Failed to resolve 'us.i.posthog.com' ([Errno 11002] getaddrinfo failed)")': /batch/
2025-07-24 13:36:25,335 - ERROR - Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020A9161B200>: Failed to resolve 'us.i.posthog.com' ([Errno 11002] getaddrinfo failed)")))
2025-07-24 13:38:29,115 - INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
2025-07-24 13:38:52,263 - INFO - Stage 1: Processing user input: Name the tools discussed in this file for evaluation
2025-07-24 13:38:52,264 - INFO - Raw user input logged: Name the tools discussed in this file for evaluation
2025-07-24 13:38:54,125 - WARNING - Ambiguous query detected: Name the tools discussed in this file for evaluation
2025-07-24 13:38:54,126 - INFO - Stage 2: Core agent execution monitoring
2025-07-24 13:38:54,126 - INFO - Action: Document retrieval initiated
2025-07-24 13:38:55,806 - INFO - Stage 3: Output generation evaluation
2025-07-24 13:38:57,802 - INFO - Response generated in 3.54 seconds
2025-07-24 13:38:57,803 - INFO - Stage 4: Final output validation
2025-07-24 13:39:42,962 - INFO - Stage 1: Processing user input: you missed phoneix evaluator tool in last response why?
2025-07-24 13:39:42,963 - INFO - Raw user input logged: you missed phoneix evaluator tool in last response why?
2025-07-24 13:39:43,595 - WARNING - Ambiguous query detected: you missed phoneix evaluator tool in last response why?
2025-07-24 13:39:43,596 - INFO - Stage 2: Core agent execution monitoring
2025-07-24 13:39:43,596 - INFO - Action: Document retrieval initiated
2025-07-24 13:39:48,160 - INFO - Stage 3: Output generation evaluation
2025-07-24 13:39:48,667 - INFO - Response generated in 5.20 seconds
2025-07-24 13:39:48,668 - INFO - Stage 4: Final output validation
2025-07-24 13:40:17,039 - INFO - Stage 1: Processing user input: name the tools named in file for evaluation
2025-07-24 13:40:17,039 - INFO - Raw user input logged: name the tools named in file for evaluation
2025-07-24 13:40:18,020 - WARNING - Ambiguous query detected: name the tools named in file for evaluation
2025-07-24 13:40:18,020 - INFO - Stage 2: Core agent execution monitoring
2025-07-24 13:40:18,021 - INFO - Action: Document retrieval initiated
2025-07-24 13:40:18,960 - WARNING - Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 50
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].
2025-07-24 13:40:21,277 - ERROR - Error in evaluation: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 50
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
]
2025-07-24 13:41:46,731 - INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
2025-07-24 13:42:04,499 - INFO - Stage 1: Processing user input: Name the tools used in file for evaluation
2025-07-24 13:42:04,499 - INFO - Raw user input logged: Name the tools used in file for evaluation
2025-07-24 13:42:06,782 - WARNING - Ambiguous query detected: Name the tools used in file for evaluation
2025-07-24 13:42:06,783 - INFO - Stage 2: Core agent execution monitoring
2025-07-24 13:42:06,783 - INFO - Action: Document retrieval initiated
2025-07-24 13:42:09,826 - INFO - Stage 3: Output generation evaluation
2025-07-24 13:42:10,353 - INFO - Response generated in 5.33 seconds
2025-07-24 13:42:10,353 - INFO - Stage 4: Final output validation
2025-07-24 13:42:45,669 - INFO - Stage 1: Processing user input: what are the 4 stages?
2025-07-24 13:42:45,669 - INFO - Raw user input logged: what are the 4 stages?
2025-07-24 13:42:46,653 - WARNING - Ambiguous query detected: what are the 4 stages?
2025-07-24 13:42:46,654 - INFO - Stage 2: Core agent execution monitoring
2025-07-24 13:42:46,655 - INFO - Action: Document retrieval initiated
2025-07-24 13:42:49,231 - INFO - Stage 3: Output generation evaluation
2025-07-24 13:42:50,298 - INFO - Response generated in 3.56 seconds
2025-07-24 13:42:50,298 - INFO - Stage 4: Final output validation
